version: '3.0'

services:
  backend:
    image: mam1zu/gc_backend
    container_name: gc-backend-container
    restart: always
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    ports:
      - "8000:8000"

  frontend:
    image: mam1zu/gc_frontend
    container_name: gc-frontend-container
    restart: always
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: gc-nginx-container
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
  